//didnt do that html myself
// let js= 'amazing';
//if (js === 'amazing') alert('JavaScript is fun');

//40 + 8 + 32 - 10
//use console.log to view results on browser
console.log(40 + 8 + 23 - 10); //colon used here is optional it is like a sentence break
console.log("jonas");
console.log("23");
//values can be stored as variables
let firstName = "Jonas"; // using variables
console.log(firstName); //whenever needed to pass the results into the browser form VS code or any other code editor we use console.log
console.log(firstName);
console.log(firstName);
//the way that has been used to assign variables here is camelcase method- 1st letter is small while other letter is capital and joined as in firstName
//eg
// console.log(firstPerson)
//also an underscore can be given while naming variables

// let 3years = 3 ; is an illegal variable naming method
// let jonas&matilda = 'JM' is also illegal due to the use of & which is unspecified symbol whereas $ can be used in a variable
// let name = 'jonas' will work without any errors but still it is illegal

let _function = 27;
let PI = 3.1415;
// all caps are used for universal constant
let myFirstJob = "Programmer";
let myCurrentJob = "Teacher";

console.log(myFirstJob);

// assignment

let $country = "Nepal";
let $continent = "Asia";
let $population = "26,494,501";

console.log($country);
console.log($continent);
console.log;

let yashName = "Dirghayu";

if (yashName === "Dirghayu") {
  console.log(`Hello This is ${yashName}`);
  yashName = "Abhinab Mishra";
  console.log(yashName);
}

function newName() {
  let yashName = 1;

  if (yashName === "1") {
    console.log(`Hello This is ${yashName}`);
    yashName = "Abhinab Mishra";
    console.log(yashName);
  }
}

newName();
